### ISSUE TITLE
Distinguishing between infectious events and factoring physical distancing time

### ISSUE THREAD

**Issue by Dosius71** [JTHooker/COVIDModel#6]
Hi Dr Thompson, thank you for making this code public. 

I am trying to understand how 'Infections events' are factored. Is this factored into 'Physical distancing - time"?

To be more clear, does this model distinguish between the following 'infectious events', and if so, how are they graded?

- Changing an aged person's diaper in a nursing home
- Nodding at a neighbour in the park as you walk past them

**Comment by JTHooker** [comment]
Hi,

In short, no it doesn’t. However, we have separate models that deal with the sorts of interactions you describe - These are currently not available in public as they have been constructed for other people / organisations such as hospitals, etc.

The issue you are really highlighting is one of scale. The model is really only targeted at a certain scale and level of decision-making. If you were a national or state government pulling large levers, this model might be of use. However, let’s say you were a hospital manager or a school principal, etc., - you’d never bother with a model that is as macro as this because you are trying to control local infection with local epidemiological / infection control, for example.

I hope that makes sense.

If you are interested in ABM, though - I would encourage you to look up some texts and even look through the sorts of articles (for free) you can get here: http://jasss.soc.surrey.ac.uk/JASSS.html .

I also have a brief explainer on some of these issues here:  https://jasonthompsondotblog.wpcomstaging.com/2020/04/03/example-post-3/

Cheers,

Jason

**Comment by Dosius71** [comment]
Hi Dr Thompson, Thank you for your prompt reply.

I will be sure to dig into the treasure trove of material - thank you! 
I guess if it's a question of granularity or scale, what would be more relevant would be to know what kind of questions the model is looking to answer.

I have read through the 10 recommendations that are based in the model (late July), and it seems that the some of the Victorian mandates go beyond the model's recommendations, like mask-wearing out in the open at distance from others, curfews that arguably condense/bottleneck peoples interactions in fewer places like supermarkets in fewer hours etc. It seems the mandates are beyond the scope of the model.

Thank you for taking the time to pass on the material.

Best,
Theo

**Comment by JTHooker** [comment]
Yes, absolutely - there is detail in the real world that can’t possibly be captured in the model. Otherwise you don’t need a model - you just use the real world.

This is something that we have always been up-front about - Have you seen the Pursuit Explainer that goes into that?

https://pursuit.unimelb.edu.au/articles/modelling-victoria-s-escape-from-covid-19

It seems to be an unfortunate issue that people think our model was some sort of super-brain thing that goes beyond human judgement - it doesn’t. It’s clever and it’s a good policy model, and it’s more sophisticated than any other we think has been used to date, but it has limitations like anything.

**Comment by Dosius71** [comment]
Having put together a 40-page blockchain whitepaper, and then producing a subsequent 3-page explainer, I appreciate the effort that goes into creating content and explainers that condense many moving parts into something that is media consumable. So thanks again for taking the time to explain here. The Pursuit Explainer does a great job of explaining the scope and limitations of the model and how it can be used as a tool none the less - and why there are discrepancies with the Victorian mandates. 

I am excited to see how this model evolves, and the boy in me would like to see a graphic Minecraft-style sim game version!

Best,
Theo
